// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 26/10/2025, 19:44:00
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/codes/sub/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codes/sub/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codes/sub/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codes/sub/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codes/sub/plugins/**/*.{js,ts,mjs}","D:/codes/sub/composables/**/*.{js,ts,mjs}","D:/codes/sub/utils/**/*.{js,ts,mjs}","D:/codes/sub/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codes/sub/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/codes/sub/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/codes/sub/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;